# Generated by Django 4.1.3 on 2022-11-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='category',
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ManyToManyField(to='category.category', verbose_name='Категории'),
        ),
    ]
